### PR TITLE
Enable Camera System to work with XR SDK / 2020.1 and above

### PR DESCRIPTION
**Pull request by FejZa**
# XRTK - Mixed Reality Toolkit Pull Request

## Overview

This PR enables the camera system to correctly work with the XR SDK plugin management and sets the camera at the correct height depending on the tracking space configuration.

## Changes

- There is a new setting for camera data providers available in their profile: `Tracking Origin Mode`. If set to `Device` the scene origin is at the device height. That means Y = 0 is where the device is. If set to "Floor", the scene origin is at floor level, that means Y = 0 is where the floor is.
- Implemented support for the XR SDK Plugin System and removed obsolete API usage
- Maintained backwards compatibility to legacy VR using scripting define symbols. Let's remove that backwards support asap once @StephenHodgson upgraded all his projects

## Related Submodule Changes

- https://github.com/XRTK/com.xrtk.lumin/pull/122
- https://github.com/XRTK/com.xrtk.sdk/pull/247
- https://github.com/XRTK/com.xrtk.oculus/pull/134
- https://github.com/XRTK/com.xrtk.wmr/pull/148
- https://github.com/XRTK/com.xrtk.oculus/pull/135

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@FejZa still failing

**Comment by FejZa** [comment]
Project builds perfectly fine locallly.

**Comment by FejZa** [comment]
Oh yeah. Actually my last commit broke something.

**Comment by StephenHodgson** [comment]
```
Packages\com.xrtk.core\Runtime\Providers\CameraSystem\BaseCameraDataProvider.cs(23,61): error CS0535: 'BaseCameraDataProvider' does not implement interface member 'IMixedRealityCameraDataProvider.HeadHeight'
```
